name: Build client and server

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build server
      working-directory: ./server
      run: mvn -B clean install package

    - name: Build client
      working-directory: ./client
      run: mvn -B clean install package

    - name: Publish JARs
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "Build"
        files: |
          ./client/target/client.jar
          ./server/target/server.jar